import com.google.android.gms.safetynet.SafetyNet;
import com.google.android.gms.safetynet.SafetyNetApi;
import com.google.android.gms.tasks.OnCompleteListener;
import com.google.android.gms.tasks.Task;

public class integrity_check_1_Req21 {

    public static void main(String args[]){
        String nonceData = "3d2fce7cdf76"; // A random value generated by your app
        ByteString nonce = ByteString.copyFromUtf8(nonceData); 

        SafetyNet.getClient(this).attest(nonce.toByteArray(), "<Your_API_Key_Here>")
        .addOnCompleteListener(new OnCompleteListener<SafetyNetApi.AttestationResponse>() {
            @Override
            public void onComplete(@NonNull Task<SafetyNetApi.AttestationResponse> task) {
                if (task.isSuccessful()) {
                    SafetyNetApi.AttestationResponse response = task.getResult();
                    byte[] attestationResponse = response.getJwsResult().getBytes();
                    // Send these bytes to your server to verify on server side.
                } else {
                    // An error occurred while communicating with the SafetyNet API
                }
            }
        });
    }
}